"""
Módulo CRUD reorganizado por dominio.
Re-exporta todas las funciones para mantener compatibilidad con `import crud`.
"""

from app.crud.crud_mesas import *
from app.crud.crud_usuarios import *
from app.crud.crud_canciones import *
from app.crud.crud_productos import *
from app.crud.crud_consumos import *
from app.crud.crud_admin import *

__all__ = [
    # crud_mesas
    "get_mesa_by_qr",
    "get_mesa_by_id",
    "get_mesas",
    "create_mesa",
    "delete_mesa",
    "set_mesa_active_status",
    "get_mesas_vacias",
    "get_table_payment_status",
    "get_all_tables_payment_status",
    "create_pago",
    "get_pagos",
    "get_pagos_mesa",
    # crud_usuarios
    "create_usuario_en_mesa",
    "create_usuario",
    "get_usuario_by_id",
    "get_usuario_by_nick",
    "get_all_usuarios",
    "update_usuario",
    "delete_usuario",
    "get_or_create_dj_user",
    "get_o_crear_usuario_admin_para_mesa",
    "get_total_consumido_por_usuario",
    "get_ranking_usuarios",
    "get_usuarios_sin_consumo",
    "get_usuarios_una_cancion",
    "get_usuarios_inactivos_consumo",
    "get_usuarios_consumen_pero_no_cantan",
    "get_usuarios_mas_rechazados",
    # crud_canciones
    "create_cancion_para_usuario",
    "get_cancion_by_id",
    "get_canciones_por_usuario",
    "get_cancion_reproduciendo",
    "get_all_canciones",
    "get_canciones_pendientes",
    "update_cancion_estado",
    "check_if_song_in_user_list",
    "get_available_song_credits",
    "get_user_credits_detail",
    "consume_song_credit",
    "get_duracion_total_cola_aprobada",
    "start_next_song_if_autoplay_and_idle",
    "check_and_approve_next_lazy_song",
    "avanzar_cola_automaticamente",
    "get_cola_lazy",
    "aprobar_siguiente_cancion_lazy",
    "get_cola_completa_con_lazy",
    "move_lazy_song_up",
    "move_lazy_song_down",
    "enriquecer_cancion",
    "get_cola_completa",
    "get_canciones_mas_cantadas",
    "get_canciones_mas_rechazadas",
    "get_canciones_cantadas_por_usuario",
    "get_canciones_cantadas_por_mesa",
    "get_actividad_por_hora",
    "get_tiempo_promedio_espera",
    "get_canciones_mas_pedidas_por_mesa",
    # crud_productos
    "get_producto_by_nombre",
    "get_producto_by_id",
    "get_all_productos",
    "get_productos",
    "create_producto",
    "update_producto",
    "delete_producto",
    "update_producto_valor",
    "update_producto_active_status",
    "get_productos_mas_consumidos",
    "get_productos_menos_consumidos",
    "get_productos_no_consumidos",
    "get_productos_mas_consumidos_por_mesa",
    # crud_consumos
    "create_consumo_para_usuario",
    "create_pedido_from_carrito",
    "get_consumos_mesa",
    "get_recent_consumos",
    "delete_consumo",
    "update_consumo_cantidad",
    "get_total_ingresos",
    "get_ganancias_totales",
    "get_ingresos_por_mesa",
    "get_ingresos_por_categoria",
    "get_ingresos_promedio_por_usuario",
    "get_ingresos_promedio_por_usuario_por_mesa",
    "get_usuarios_mayor_gasto_por_categoria",
    "get_top_consumers_one_song",
    "get_resumen_noche",
    "get_categorias_mas_consumidas_por_mesa",
    # crud_admin
    "create_admin_api_key",
    "get_admin_api_key",
    "get_all_admin_api_keys",
    "deactivate_admin_api_key",
    "delete_admin_api_key",
    "reset_database_for_new_night",
    "limpiar_datos_prueba",
]
